[project]
name = "pv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ctx400", email = "43049420+ctx400@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "attrs>=25.3.0",
    "cattrs>=24.1.3",
    "cryptography>=44.0.3",
]

[project.scripts]
pv = "pv:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
